version: 1

update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
